module.exports=[,{
    path:'/finance-report',
    component:function(resolve){
        require.ensure(['view/finance-report'],function(){
            resolve(require('view/finance-report/index.vue').default)
        },'finance-report')
    }
},{
    path:'/investor',
    component:require('view/investor/index.vue').default
},{
    path:'/organization',
    component:require('view/organization/index.vue').default
},{
    path:'/industry',
    component:require('view/industry/index.vue').default
},{
    path:'/redashData',
    component:require('view/redashData/index.vue').default
}];